config/routes.rb
Rails.application.routes.draw do
  root 'pokemons#index'
  get 'pokemons', to: 'pokemons#index'
  get 'pokemons/:id', to: 'pokemons#show', as: 'pokemon'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pokemons_controller.rb
require 'net/http'
require 'json'

class PokemonsController < ApplicationController
  def index
  end

  def show
    @pokemon_id_or_name = params[:id]
    Rails.logger.debug "Received id: #{@pokemon_id_or_name}"
    @pokemon_data = fetch_pokemon_data(@pokemon_id_or_name)
    if @pokemon_data.nil?
      flash[:alert] = "ポケモンが見つかりませんでした。"
      redirect_to root_path
    else
      Rails.logger.debug "Fetched Pokemon Data: #{@pokemon_data}"
    end
  end

  private

  def fetch_pokemon_data(id_or_name)
    url = URI("https://pokeapi.co/api/v2/pokemon/#{id_or_name}/")
    response = Net::HTTP.get(url)
    JSON.parse(response) rescue nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pokemove" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>ポケモンデータ表示アプリ</h1>
<%= form_with(url: pokemon_path('dummy'), method: :get, local: true) do %>
  <%= label_tag :id, "ポケモンのIDまたは名前を入力" %>
  <%= text_field_tag :id %>
  <%= submit_tag "検索" %>
<% end %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon_data['name'].capitalize %> (ID: <%= @pokemon_data['id'] %>)</h1>
<img src="<%= @pokemon_data['sprites']['front_default'] %>" alt="<%= @pokemon_data['name'] %>">
<p><strong>高さ:</strong> <%= @pokemon_data['height'] %></p>
<p><strong>重さ:</strong> <%= @pokemon_data['weight'] %></p>
<p><strong>特性:</strong> <%= @pokemon_data['abilities'].map { |ability| ability['ability']['name'] }.join(', ') %></p>
<p><strong>種族値:</strong></p>
<ul>
  <% @pokemon_data['stats'].each do |stat| %>
    <li><%= stat['stat']['name'] %>: <%= stat['base_stat'] %></li>
  <% end %>
</ul>
<%= link_to '戻る', root_path %>